# Generated by Django 4.2.5 on 2023-10-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_snp_alter_contacts_email_alter_contacts_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
