# Generated by Django 4.2.5 on 2023-10-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_forum_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='uid',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
