# Generated by Django 4.2.5 on 2023-10-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_forum_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='uid',
        ),
    ]
