# Generated by Django 4.2.5 on 2023-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_forum_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='prk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fltn', models.CharField(max_length=50)),
                ('prkno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('emp', models.BooleanField(default=False)),
                ('d_in', models.CharField(max_length=100)),
                ('d_out', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=50)),
                ('wing', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='snp',
            name='fltn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
