# Generated by Django 4.2.5 on 2023-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_event_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='trck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('fltn', models.CharField(max_length=122)),
                ('wi', models.IntegerField(max_length=122)),
                ('altp', models.IntegerField(max_length=122)),
                ('intime', models.DateTimeField(auto_now_add=True, null=True)),
                ('outtime', models.DateTimeField()),
            ],
        ),
    ]
