# Generated by Django 4.2.5 on 2023-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_trck'),
    ]

    operations = [
        migrations.AddField(
            model_name='trck',
            name='phno',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='trck',
            name='altp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trck',
            name='wi',
            field=models.IntegerField(),
        ),
    ]
