# Generated by Django 4.2.5 on 2023-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_trck_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trck',
            name='alotpark',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='trck',
            name='altp',
            field=models.CharField(null=True),
        ),
    ]
