# Generated by Django 4.2.5 on 2023-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_trck_alotpark_alter_trck_altp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trck',
            name='wi',
            field=models.CharField(null=True),
        ),
    ]
