# Generated by Django 4.2.5 on 2023-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_snp_priv'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='snp',
            name='priv',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
